// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestor_tareas_api.Data;

#nullable disable

namespace gestor_tareas_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813234810_AddUsuarioImagenPerfil")]
    partial class AddUsuarioImagenPerfil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gestor_tareas_api.Models.Adjunto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaRelativa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TamañoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TareaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.ToTable("Adjuntos");
                });

            modelBuilder.Entity("gestor_tareas_api.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("TareaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("gestor_tareas_api.Models.MiembroProyecto", b =>
                {
                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("ProyectoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MiembrosProyectos");

                    b.HasData(
                        new
                        {
                            ProyectoId = 1,
                            UsuarioId = 1,
                            Rol = 0
                        },
                        new
                        {
                            ProyectoId = 2,
                            UsuarioId = 2,
                            Rol = 0
                        },
                        new
                        {
                            ProyectoId = 1,
                            UsuarioId = 2,
                            Rol = 1
                        });
                });

            modelBuilder.Entity("gestor_tareas_api.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Descripción")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PropietarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropietarioId");

                    b.ToTable("Proyectos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FF5733",
                            Descripción = "Proyecto Capstone final",
                            FechaCreacion = new DateTime(2026, 8, 13, 23, 48, 10, 171, DateTimeKind.Utc).AddTicks(4608),
                            Nombre = "Sistema Trello Clon",
                            PropietarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#33FF57",
                            Descripción = "Proyecto de revisión",
                            FechaCreacion = new DateTime(2026, 8, 13, 23, 48, 10, 171, DateTimeKind.Utc).AddTicks(4609),
                            Nombre = "Auditoría de Software",
                            PropietarioId = 2
                        });
                });

            modelBuilder.Entity("gestor_tareas_api.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Revocado")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("gestor_tareas_api.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsignadoAId")
                        .HasColumnType("int");

                    b.Property<string>("Descripción")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("Título")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AsignadoAId = 1,
                            Descripción = "Crear modelos en EF Core",
                            Estado = 2,
                            Prioridad = 2,
                            ProyectoId = 1,
                            Título = "Diseñar Base de Datos"
                        },
                        new
                        {
                            Id = 2,
                            AsignadoAId = 1,
                            Descripción = "Configurar autenticación",
                            Estado = 1,
                            Prioridad = 2,
                            ProyectoId = 1,
                            Título = "Implementar JWT"
                        },
                        new
                        {
                            Id = 3,
                            AsignadoAId = 2,
                            Descripción = "Componentes Kanban",
                            Estado = 0,
                            Prioridad = 1,
                            ProyectoId = 1,
                            Título = "Crear UI en React"
                        },
                        new
                        {
                            Id = 4,
                            AsignadoAId = 2,
                            Descripción = "Leer el documento base",
                            Estado = 2,
                            Prioridad = 0,
                            ProyectoId = 2,
                            Título = "Revisión de requerimientos"
                        },
                        new
                        {
                            Id = 5,
                            AsignadoAId = 2,
                            Descripción = "Documentar hallazgos",
                            Estado = 0,
                            Prioridad = 1,
                            ProyectoId = 2,
                            Título = "Redactar informe"
                        });
                });

            modelBuilder.Entity("gestor_tareas_api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "rayber@admin.com",
                            FechaRegistro = new DateTime(2026, 8, 13, 23, 48, 10, 171, DateTimeKind.Utc).AddTicks(4488),
                            Nombre = "Rayber",
                            PasswordHash = "hash_temporal_123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "merali@user.com",
                            FechaRegistro = new DateTime(2026, 8, 13, 23, 48, 10, 171, DateTimeKind.Utc).AddTicks(4490),
                            Nombre = "Merali",
                            PasswordHash = "hash_temporal_456"
                        });
                });

            modelBuilder.Entity("gestor_tareas_api.Models.Adjunto", b =>
                {
                    b.HasOne("gestor_tareas_api.Models.Tarea", "Tarea")
                        .WithMany("Adjuntos")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("gestor_tareas_api.Models.Comentario", b =>
                {
                    b.HasOne("gestor_tareas_api.Models.Tarea", "Tarea")
                        .WithMany("Comentarios")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestor_tareas_api.Models.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("gestor_tareas_api.Models.MiembroProyecto", b =>
                {
                    b.HasOne("gestor_tareas_api.Models.Proyecto", "Proyecto")
                        .WithMany("Miembros")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestor_tareas_api.Models.Usuario", "Usuario")
                        .WithMany("Membresias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("gestor_tareas_api.Models.Proyecto", b =>
                {
                    b.HasOne("gestor_tareas_api.Models.Usuario", "Propietario")
                        .WithMany("ProyectosPropios")
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("gestor_tareas_api.Models.RefreshToken", b =>
                {
                    b.HasOne("gestor_tareas_api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("gestor_tareas_api.Models.Tarea", b =>
                {
                    b.HasOne("gestor_tareas_api.Models.Usuario", "AsignadoA")
                        .WithMany("TareasAsignadas")
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("gestor_tareas_api.Models.Proyecto", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignadoA");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("gestor_tareas_api.Models.Proyecto", b =>
                {
                    b.Navigation("Miembros");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("gestor_tareas_api.Models.Tarea", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("gestor_tareas_api.Models.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Membresias");

                    b.Navigation("ProyectosPropios");

                    b.Navigation("TareasAsignadas");
                });
#pragma warning restore 612, 618
        }
    }
}
